language: erlang
otp_release:
  - 17.3
  - 17.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R15B03
  - R15B02
  - R15B01
  - R14B04
  - R14B03

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y autotools-dev libpam0g-dev erlang-yaws

install:
  - autoreconf -vfi

before_script:
  - ERL_LIBS="/usr/lib:$ERL_LIBS" ./configure

script:
  - ERL_LIBS="/usr/lib:$ERL_LIBS" make distcheck -j4 V=1

after_script:
  - rebar get-deps
  - rebar compile && rebar skip_deps=true ct
